### ISSUE TITLE
Import Packet

### ISSUE THREAD

**Issue by jiaqifan123** [J1nqianChen/APH#1]
Dear author, when I downloaded the code and then imported the package to run, I found that there were some packages that could not be imported, such as: ”from uncertain. APH_ood_eval import check_pfl“, “from Read_Data import select_read“, “from Uncertainty.Fine_Tune_Head import rearrange_model_all“, “from Uncertainty.uncertainty_utils import evaluate_from_head, aggregate_out, evaluate_aph“, hope you can provide the repository of these packages. By the way, when will the full guidelines go live？

**Comment by J1nqianChen** [comment]
Hi Qifan,
Thank you for your attention. Apologies for the delay; I've been busy with deadlines recently. I will complete the code and guidelines today. After the completion, I will notice you.

**Comment by jiaqifan123** [comment]
Thank you very much

**Comment by jiaqifan123** [comment]
Hello, author, I'm sorry to bother you again, I have a problem, I hope to get your help. I would like to know how the ACC value is defined in this implementation, is it a global ACC value or an average of ACC values across client models, or something else?

**Comment by J1nqianChen** [comment]
Hi Qifan:
I'm so sorry to finish the code so late. A simplified version of APH is available now. I will compensente the training part of federated models soon. Currently, APH can only support the training and calibration of existed models. 

For your question, the accuracy is computed as the averaged acc of all clients in their local datasets. 

If you have further questions, please feel free to ask.

My apologies again.
